site_name: elecadvisor
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Backend: backend.md
  - Forecasting Flow: ../docs/forecast_project/FORECASTING_FLOW.md
  - Design: design.md
  - Plan: plan.md
  - Background: background.md
  - Progress: progress.md

